### ISSUE TITLE
actions/create-releaseをメンテナンスされてるやつに置き換える

### ISSUE THREAD

**Issue by book000** [book000/templates#103]
https://github.com/book000/templates/blob/master/.github/workflows/reusable-docker.yml

https://github.com/marketplace/actions/create-release

---

https://github.com/search?q=org%3Abook000+OR+org%3Atomacheese+OR+org%3Ajaoafa+create-release&type=code

**Comment by book000** [comment]
オプションの確認とか必要。

**Comment by book000** [comment]
| actions/create-release | ncipollo/release-action |
|:-|:-|
| tag_name | tag |
| release_name | name |
| body | body |
| body_path | bodyFile |
| draft | draft |
| prerelease | prerelease |
| commitish | commit |
| owner | owner |
| repo | repo |

```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.calc-version.outputs.tag }}
          release_name: ${{ needs.calc-version.outputs.tag }}
          body: ${{ needs.calc-version.outputs.changelog }}
          draft: false
          prerelease: false
```

```
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.calc-version.outputs.tag }}
          name: ${{ needs.calc-version.outputs.tag }}
          body: ${{ needs.calc-version.outputs.changelog }}
          draft: false
          prerelease: false
```
